### ISSUE TITLE
another element <tp-yt-iron-overlay-backdrop class="opened"> obscures it

### ISSUE THREAD

**Issue by xiaoxinhuozhu** [ContentAutomation/YouTubeUploader#11]
I am a newbie.I keep having the following problem, but with the same configuration, my other machine is working fine.
`Using python3.8 (3.8.2)
Traceback (most recent call last):
  File "main.py", line 137, in <module>
    main()
  File "main.py", line 47, in main
    upload_file(
  File "/root/up/YouTubeUploader/src/upload.py", line 33, in upload_file
    _set_advanced_settings(driver, game, kids)
  File "/root/up/YouTubeUploader/src/upload.py", line 118, in _set_advanced_settings
    WebDriverWait(driver, 20).until(EC.element_to_be_clickable(
  File "/root/.cache/pypoetry/virtualenvs/youtubeuploader-qpcdujY--py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/root/.cache/pypoetry/virtualenvs/youtubeuploader-qpcdujY--py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/root/.cache/pypoetry/virtualenvs/youtubeuploader-qpcdujY--py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/root/.cache/pypoetry/virtualenvs/youtubeuploader-qpcdujY--py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <tp-yt-paper-radio-button class="style-scope ytcp-audience-picker" name="NOT_MADE_FOR_KIDS"> is not clickable at point (626,781) because another element <tp-yt-iron-overlay-backdrop class="opened"> obscures it`
After checking, I know the problem is here, but I still don't know how to solve it. Could you help me
`   WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.CSS_SELECTOR, "ytcp-button#create-icon"))).click()`

**Comment by MorMundHS-MA** [comment]
This is unfortunately the same issue as #8. Google sometimes requires verification, which we cannot automate at the moment.
