### ISSUE TITLE
assert "Channel dashboard" in driver.title

### ISSUE THREAD

**Issue by VitharMe** [ContentAutomation/YouTubeUploader#5]
At this point it fails:
```bash
root@localhost:~/YouTubeUploader# poetry run python main.py --browser docker --login-cookies-path /root/YouTubeUploader/cookie.json --title test --description test /uploads/video.mp4
The currently activated Python version 3.7.3 is not supported by the project (~3.8).
Trying to find and use a compatible version.
Using python3.8 (3.8.3)
Traceback (most recent call last):
  File "main.py", line 137, in <module>
    main()
  File "main.py", line 45, in main
    assert "Channel dashboard" in driver.title
AssertionError
```
```
firefox_1  | 2021-06-01 10:19:00,040 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
firefox_1  | 2021-06-01 10:19:00,046 INFO supervisord started with pid 10
firefox_1  | 2021-06-01 10:19:01,053 INFO spawned: 'xvfb' with pid 12
firefox_1  | 2021-06-01 10:19:01,065 INFO spawned: 'selenium-standalone' with pid 13
firefox_1  | 2021-06-01 10:19:02,079 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
firefox_1  | 2021-06-01 10:19:02,080 INFO success: selenium-standalone entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
firefox_1  | 10:19:02.107 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
firefox_1  | 10:19:02.408 INFO [GridLauncherV3.lambda$buildLaunchers$3] - Launching a standalone Selenium Server on port 4444
firefox_1  | 2021-06-01 10:19:02.588:INFO::main: Logging initialized @1479ms to org.seleniumhq.jetty9.util.log.StdErrLog
firefox_1  | 10:19:03.286 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
firefox_1  | 10:19:03.581 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
firefox_1  | 10:19:07.231 INFO [ActiveSessionFactory.apply] - Capabilities are: {
firefox_1  |   "acceptInsecureCerts": true,
firefox_1  |   "browserName": "firefox",
firefox_1  |   "marionette": true
firefox_1  | }
firefox_1  | 10:19:07.242 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
firefox_1  | 1622542747308      geckodriver     INFO    Listening on 127.0.0.1:5100
firefox_1  | 1622542748191      mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "--marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileW4SxKL"
firefox_1  | [GFX1-]: glxtest: libpci missing
firefox_1  | [GFX1-]: glxtest: libEGL missing
firefox_1  | [GFX1-]: glxtest: libEGL missing
firefox_1  | 1622542749234      Marionette      INFO    Marionette enabled
firefox_1  | console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
firefox_1  | 1622542753474      Marionette      INFO    Listening on port 35839
firefox_1  | 1622542753597      Marionette      WARN    TLS certificate errors will be ignored for this session
firefox_1  | 10:19:13.757 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
firefox_1  | 10:19:13.973 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 10dbd24c-c628-46ab-a407-1c9544b56f74 (org.openqa.selenium.firefox.GeckoDriverService)
firefox_1  | 1622542766546      Marionette      INFO    Stopped listening on port 35839
firefox_1  | JavaScript error: https://studio.youtube.com/s/6641c24f/creator_studio_mod_binary_core_v2.es.js, line 21003: NS_ERROR_NOT_INITIALIZED:
firefox_1  | JavaScript error: https://studio.youtube.com/s/6641c24f/creator_studio_mod_binary_core_v2.es.js, line 21003: NS_ERROR_NOT_INITIALIZED:
firefox_1  | JavaScript error: https://studio.youtube.com/s/6641c24f/creator_studio_mod_binary_core_v2.es.js, line 21003: NS_ERROR_NOT_INITIALIZED:
firefox_1  | JavaScript error: https://studio.youtube.com/s/6641c24f/creator_studio_mod_binary_core_v2.es.js, line 21003: NS_ERROR_NOT_INITIALIZED:
firefox_1  | JavaScript error: https://studio.youtube.com/s/6641c24f/creator_studio_mod_binary_core_v2.es.js, line 21003: NS_ERROR_NOT_INITIALIZED:
firefox_1  | JavaScript error: resource:///modules/FaviconLoader.jsm, line 596: InvalidStateError: JSWindowActorChild.sendAsyncMessage: JSWindowActorChild cannot send at the moment
firefox_1  | JavaScript error: resource:///modules/FaviconLoader.jsm, line 596: InvalidStateError: JSWindowActorChild.sendAsyncMessage: JSWindowActorChild cannot send at the moment
firefox_1  |
firefox_1  | ###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost
firefox_1  |
firefox_1  |
firefox_1  | ###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost
firefox_1  |
firefox_1  |
firefox_1  | ###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost
firefox_1  |
firefox_1  |
firefox_1  | ###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost
firefox_1  |
firefox_1  |
firefox_1  | ###!!! [Parent][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost
```

**Comment by ChristianCoenen** [comment]
Can you try to run it locally (installing chromedriver and using chrome for example)? If you do so, I'd. recommend setting a breakpoint at line 45 and checking the title of the tab that opens (the program checks if it includes the name 'Channel dashboard').

I assume that for some reason the login didn't work properly even though no exception was thrown. Therefore. you're not logged in when the uploader opens the yt studio page.

**Comment by VitharMe** [comment]
> 
> 
> Can you try to run it locally (installing chromedriver and using chrome for example)? If you do so, I'd. recommend setting a breakpoint at line 45 and checking the title of the tab that opens (the program checks if it includes the name 'Channel dashboard').
> 
> I assume that for some reason the login didn't work properly even though no exception was thrown. Therefore. you're not logged in when the uploader opens the yt studio page.

I've used:
```python
get_title = driver.title
```
I realized that I had the account in another language.
Thanks!
