### ISSUE TITLE
Message: Unable to locate element: div.card:nth-child(1)

### ISSUE THREAD

**Issue by VitharMe** [ContentAutomation/YouTubeUploader#6]
At this point it fails:
```bash
root@localhost:~/YouTubeUploader#  poetry run python main.py --browser docker --login-cookies-path /root/YouTubeUploader/cookie.json --title test --description test /uploads/video.mp4
The currently activated Python version 3.7.3 is not supported by the project (~3.8).
Trying to find and use a compatible version.
Using python3.8 (3.8.3)
INFO:root:Current progress: Processing 99% ...
Traceback (most recent call last):
  File "main.py", line 140, in <module>
    main()
  File "main.py", line 50, in main
    upload_file(
  File "/root/YouTubeUploader/src/upload.py", line 41, in upload_file
    _set_endcard(driver)
  File "/root/YouTubeUploader/src/upload.py", line 128, in _set_endcard
    driver.find_element_by_css_selector("div.card:nth-child(1)").click()
  File "/root/.cache/pypoetry/virtualenvs/youtubeuploader-daD3CONG-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/root/.cache/pypoetry/virtualenvs/youtubeuploader-daD3CONG-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/root/.cache/pypoetry/virtualenvs/youtubeuploader-daD3CONG-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/root/.cache/pypoetry/virtualenvs/youtubeuploader-daD3CONG-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: div.card:nth-child(1)
```
```bash
firefox_1  | 19:53:45.359 INFO [ActiveSessionFactory.apply] - Capabilities are: {
firefox_1  |   "acceptInsecureCerts": true,
firefox_1  |   "browserName": "firefox",
firefox_1  |   "marionette": true
firefox_1  | }
firefox_1  | 19:53:45.362 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
firefox_1  | 1622663625413      geckodriver     INFO    Listening on 127.0.0.1:30806
firefox_1  | 1622663625478      mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "--marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileiG64GG"
firefox_1  | [GFX1-]: glxtest: libpci missing
firefox_1  | [GFX1-]: glxtest: libEGL missing
firefox_1  | [GFX1-]: glxtest: libEGL missing
firefox_1  | 1622663626690      Marionette      INFO    Marionette enabled
firefox_1  | console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
firefox_1  | 1622663631333      Marionette      INFO    Listening on port 37591
firefox_1  | 1622663631541      Marionette      WARN    TLS certificate errors will be ignored for this session
firefox_1  | 19:53:51.639 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
firefox_1  | 19:53:51.659 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session b63d226a-120f-47f9-b143-fd1f0802cac9 (org.openqa.selenium.firefox.GeckoDriverService)
firefox_1  | 1622663652978      Marionette      WARN    TimedPromise timed out after 500 ms: stacktrace:
firefox_1  | TimedPromise/<@chrome://marionette/content/sync.js:237:19
firefox_1  | TimedPromise@chrome://marionette/content/sync.js:222:10
firefox_1  | interaction.flushEventLoop@chrome://marionette/content/interaction.js:431:10
firefox_1  | webdriverClickElement@chrome://marionette/content/interaction.js:179:31
firefox_1  | 1622663654427      Marionette      WARN    TimedPromise timed out after 500 ms: stacktrace:
firefox_1  | TimedPromise/<@chrome://marionette/content/sync.js:237:19
firefox_1  | TimedPromise@chrome://marionette/content/sync.js:222:10
firefox_1  | interaction.flushEventLoop@chrome://marionette/content/interaction.js:431:10
firefox_1  | webdriverClickElement@chrome://marionette/content/interaction.js:179:31
firefox_1  | 1622663674728      Marionette      WARN    TimedPromise timed out after 500 ms: stacktrace:
firefox_1  | TimedPromise/<@chrome://marionette/content/sync.js:237:19
firefox_1  | TimedPromise@chrome://marionette/content/sync.js:222:10
firefox_1  | interaction.flushEventLoop@chrome://marionette/content/interaction.js:431:10
firefox_1  | webdriverClickElement@chrome://marionette/content/interaction.js:179:31
firefox_1  | 1622663676936      Marionette      WARN    TimedPromise timed out after 500 ms: stacktrace:
firefox_1  | TimedPromise/<@chrome://marionette/content/sync.js:237:19
firefox_1  | TimedPromise@chrome://marionette/content/sync.js:222:10
firefox_1  | interaction.flushEventLoop@chrome://marionette/content/interaction.js:431:10
firefox_1  | webdriverClickElement@chrome://marionette/content/interaction.js:179:31
firefox_1  | 1622663700668      Marionette      INFO    Stopped listening on port 37591
firefox_1  |
firefox_1  | ###!!! [Parent][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost
firefox_1  |
```

![sdfv](https://user-images.githubusercontent.com/34602541/120544478-bf5ada80-c3ed-11eb-878a-a2c485734091.png)

**Comment by ChristianCoenen** [comment]
Thanks for reporting this issue. I couldn't reproduce it both locally and via docker. However, I think it is related to clicking an element before it is loaded. I've created a pull request that addresses the issue.

@VitharMe could you try if the PR solves the problem?
