### ISSUE TITLE
Verify It's You

### ISSUE THREAD

**Issue by sinzed** [ContentAutomation/YouTubeUploader#8]
Hi,
Thank you for your effort.
it works good when using Browsers but on Docker it stops with the error

`Traceback (most recent call last):
  File "./main.py", line 139, in <module>
    main()
  File "./main.py", line 48, in main
    upload_file(
  File "/root/project-name/YouTubeUploader/src/upload.py", line 36, in upload_file
    _set_advanced_settings(driver, game, kids)
  File "/root/project-name/YouTubeUploader/src/upload.py", line 150, in _set_advanced_settings
    WebDriverWait(driver, 20).until(EC.element_to_be_clickable(
  File "/root/.cache/pypoetry/virtualenvs/youtubeuploader-qf-YjOKG-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/root/.cache/pypoetry/virtualenvs/youtubeuploader-qf-YjOKG-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/root/.cache/pypoetry/virtualenvs/youtubeuploader-qf-YjOKG-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/root/.cache/pypoetry/virtualenvs/youtubeuploader-qf-YjOKG-py3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <div id="radioContainer" class="style-scope tp-yt-paper-radio-button"> is not clickable at point (539,793) because another element <tp-yt-iron-overlay-backdrop class="opened"> obscures it
`

![image](https://user-images.githubusercontent.com/26181990/121715377-18f29180-cadf-11eb-8bd3-980bbf6ac2dd.png)

`docker -v
Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2`

`docker-compose -v
docker-compose version 1.25.0, build unknown`

`poetry -v
Poetry version 1.1.6`

`python3 --version
Python 3.8.5`

**Comment by sinzed** [comment]
is there anyway to open the browser (remote web-driver) of docker-compose manually and do the verification?

**Comment by ChristianCoenen** [comment]
Hey. Thanks for reporting. I encountered this as well (two days ago) and hoped it was just related to my account, but seems Google added another security layer there.

I have no idea right now how to fix this because the verification is not possible through an automated browser instance and it even happened to me with completely fresh cookies.

> 
is there anyway to open the browser (remote web-driver) of docker-compose manually and do the verification?
> 
@MorMundHS-MA any ideas about whether something like this would be possible/could work?

**Comment by MorMundHS-MA** [comment]
> any ideas about whether something like this would be possible/could work?

You can access the browser UI inside the container, however since its a selenium session, the login would still be blocked by Google. And as far as I know Selenium creates a new profile on startup, so you can't verify without selenium ahead of time. 

We could see if its possible with Selenium to use a complete Firefox profile, which could be verified outside of the container. But Google might still just check for automated browsers and show the verification anyway.

**Comment by rzfzr** [comment]
I recently encounted the same issue, selenium on js, not python. Switching the agent to firefox did nothing, I tried to save/load the browser session to disk instead of loading the cookie everythime, same thing.
The only thing that worked was deleting the whole html element, you can try with the developer tools open, just select and delete, it will let you keep using the site.
But it seems very hacky, I gave up working with it in fear of banning, I applied for higher credits on the official API....

**Comment by fais3000** [comment]
I'm also getting stuck here. I wish there is a workaround for this. Adding video descriptions manually is a pain :(

**Comment by lengrongfu** [comment]
> 我最近遇到了同样的问题，js 上的 selenium，而不是 python。将代理切换到 firefox 什么也没做，我尝试将浏览器会话保存/加载到磁盘，而不是每次都加载 cookie，同样的事情。 唯一有效的是删除整个 html 元素，您可以尝试打开开发人员工具，只需选择并删除，它就会让您继续使用该站点。 但它似乎很hacky，我因为害怕被禁止而放弃了使用它，我在官方API上申请了更高的信用......

申请更高数量的API是否需要支付钱，这个目前是怎么回事呢。 @rzfzr

**Comment by catears124** [comment]
any fix yet? i cant get this working

**Comment by ChristianCoenen** [comment]
Unfortunately no. Haven't looked into it since, but I don't see a quick and easy solution to this.

**Comment by rzfzr** [comment]
I don't recommend pursuing this, I'm afraid of getting banned.
Currently I use both the official api and an chrome extension I developed for manipulating the site with js
